services:
#  rabbitmq:
#    container_name: rabbitmq-producer
#    image: rabbitmq:management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - producer-network

  database:
    image: 'postgres:13.1-alpine'
    container_name: postgresql-producer
    restart: always
    environment:
      POSTGRES_DB: producer-db
      POSTGRES_USER: ronaldo
      POSTGRES_PASSWORD: ronaldo
    command: -p 5436
    ports:
      - "5438:5436"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ronaldo -d producer-db -p 5436" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - producer-network

networks:
  producer-network:
    name: producer-network
    driver: bridge
  scs-network:
    # Indica que esta rede já existe e foi criada externamente
    # Geralmente usada para comunicação com outros serviços como RabbitMQ
    external: true